In [2]:
import pandas as ps
import numpy as ny

In [6]:
q=ny.array([2,5,8,1,5,9])

In [7]:
type(q)

numpy.ndarray

- Here, nd array means n dimensional array. Eg : 1-d , 2-d , 3-d.....,n-d array

In [13]:
y=ny.array([1,-7,'wrt',3+7j,5,3.3])

In [14]:
y

array(['1', '-7', 'wrt', '(3+7j)', '5', '3.3'], dtype='<U64')

In [18]:
ny.array([2,4,1,5.23,8])

array([2.  , 4.  , 1.  , 5.23, 8.  ])

- We can change the datatype of array using dtype

In [24]:
ny.array([1,3,4],dtype=complex) 

array([1.+0.j, 3.+0.j, 4.+0.j])

In [18]:
ar1=ny.array([[(1, 2),(3, 4)]])

 - We can create numpy array in Small(1, 2) / Big [2,4] braces

In [19]:
ar1

array([[[1, 2],
        [3, 4]]])

In [20]:
ny.mat(ar1)

matrix([[1, 2],
        [3, 4]])

In [31]:
ar2=ny.mat(ar1)

In [25]:
e=[1,2,3,'tnb',0.72]

In [35]:
ny.asarray(e)

array(['1', '2', '3', 'tnb', '0.72'], dtype='<U32')

In [34]:
ny.asanyarray(e)

array(['1', '2', '3', 'tnb', '0.72'], dtype='<U32')

1. Differ b/w asarray converts everything to array & asanyarray only converts those which r not predefined array
2. matrix is subset of array.it can be checked using ' issubclass '.

In [3]:
e1=ny.array([[[4,7,2],[9,0,5]],[[9,0,5],[6,1,8]]])

In [4]:
e1

array([[[4, 7, 2],
        [9, 0, 5]],

       [[9, 0, 5],
        [6, 1, 8]]])

In [5]:
e1.ndim

3

In [6]:
e1.size

12

In [7]:
e1.shape

(2, 2, 3)

In [ ]:
1. .shape() shows the set of element & its dimension. Here (2,2,3) means 1st 2 means 2 set of elements,
2. 2nd (2,3) means its dimension i.e n x m .

In [18]:
q1=ny.array([u**u for u in range(5)])
ps.DataFrame(q1)


0
0    1
1    1
2    4
3   27
4  256

numpy.from...() is use to generate  ndarray()

In [27]:
ny.fromiter(range(7),dtype=complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [43]:
ny.fromstring('234 574 23 768 356', sep = ' ' ,dtype=int)

array([234, 574,  23, 768, 356])

In [44]:
e1.dtype

dtype('int32')

In [45]:
e1.size

12

In [49]:
# Q 1. empty array
a=ny.empty([3,3], dtype=int)
a

[[         0          0 1318772816]
 [     32762          1          0]
 [        -1         -1          0]]


In [52]:
# q 2. full array
b=ny.full([3,3],78, dtype=int)
b

array([[78, 78, 78],
       [78, 78, 78],
       [78, 78, 78]])

In [61]:
# 3. zeros
c=ny.zeros([3,3], dtype=int)
c
# d=ny.ones([3,3], dtype=int)
# d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [78]:
# 4. check specified row.
e=ny.array([[1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
            [11, 12, 13, 14, 15],
            [16, 17, 18, 19, 20]])


In [80]:
print([1,2,3,4,5] in e.tolist())

False


In [86]:
# acessing element using index notation
# e[2,3]
# or ,both gives same o/p
e[2][3]

14

In [93]:
# removing null values
f=ny.array([[2,9,3,0],[ny.nan,8,ny.nan,3],[ny.nan,6,1,ny.nan]])
f

array([[ 2.,  9.,  3.,  0.],
       [nan,  8., nan,  3.],
       [nan,  6.,  1., nan]])

In [102]:
ny.isnan(f)  # row wise nan values

array([[False, False, False, False],
       [ True, False,  True, False],
       [ True, False, False,  True]])

In [103]:
ny.isnan(f).any(axis=1) # column wise nan values 

array([False,  True,  True])

In [104]:
# Numpy has arange function to print values in a given range
ny.arange(2.1,8,.5)

array([2.1, 2.6, 3.1, 3.6, 4.1, 4.6, 5.1, 5.6, 6.1, 6.6, 7.1, 7.6])

In [111]:
ny.arange(1,8,.7)

array([1. , 1.7, 2.4, 3.1, 3.8, 4.5, 5.2, 5.9, 6.6, 7.3])

In [120]:
ny.linspace(1,17,17)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17.])

In [126]:
ny.linspace(24,33,2,retstep=True)

(array([24., 33.]), 9.0)

linspace creates even distribution between a given range().

In [6]:
ny.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
ny.linspace(1,25,50)

array([ 1.        ,  1.48979592,  1.97959184,  2.46938776,  2.95918367,
        3.44897959,  3.93877551,  4.42857143,  4.91836735,  5.40816327,
        5.89795918,  6.3877551 ,  6.87755102,  7.36734694,  7.85714286,
        8.34693878,  8.83673469,  9.32653061,  9.81632653, 10.30612245,
       10.79591837, 11.28571429, 11.7755102 , 12.26530612, 12.75510204,
       13.24489796, 13.73469388, 14.2244898 , 14.71428571, 15.20408163,
       15.69387755, 16.18367347, 16.67346939, 17.16326531, 17.65306122,
       18.14285714, 18.63265306, 19.12244898, 19.6122449 , 20.10204082,
       20.59183673, 21.08163265, 21.57142857, 22.06122449, 22.55102041,
       23.04081633, 23.53061224, 24.02040816, 24.51020408, 25.        ])

In [66]:
ny.random.randint(0,999,(4,6))

array([[470, 454, 998, 586, 991, 604],
       [905, 722, 228, 708, 262, 469],
       [787, 500, 869, 905, 392, 516],
       [272, 410, 573, 919,  50, 841]])

In [87]:
wx=ny.random.randint(1,57,(4,2))
wx

array([[50,  9],
       [14, 24],
       [ 1, 50],
       [34, 29]])

In [102]:
wx.reshape(8,-349898934521)

array([[50],
       [ 9],
       [14],
       [24],
       [ 1],
       [50],
       [34],
       [29]])

In [103]:
wx.min()

1

In [104]:
wx.max()

50

In [110]:
wx[2:,1:]

array([[50],
       [29]])

In [116]:
wx>50

array([[False, False],
       [False, False],
       [False, False],
       [False, False]])

In [117]:
wx[wx>17]

array([50, 24, 50, 34, 29])

In [125]:
t1=ny.random.randint(1,9,(3,2))
t1

array([[4, 1],
       [5, 3],
       [6, 7]])

In [126]:
t2=ny.random.randint(1,9,(3,2))
t2

array([[3, 8],
       [3, 3],
       [1, 4]])

In [127]:
t1*t2

array([[12,  8],
       [15,  9],
       [ 6, 28]])

In [134]:
t3=ny.zeros((3,3))
t3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [135]:
t4=ny.array([5,1,8])

In [136]:
t3+t4

array([[5., 1., 8.],
       [5., 1., 8.],
       [5., 1., 8.]])

In [143]:
t5=t4.reshape(3,1)+t3
t5

array([[5., 5., 5.],
       [1., 1., 1.],
       [8., 8., 8.]])

In [144]:
ny.sqrt(t5)

array([[2.23606798, 2.23606798, 2.23606798],
       [1.        , 1.        , 1.        ],
       [2.82842712, 2.82842712, 2.82842712]])

In [145]:
ny.exp(t5)

array([[1.48413159e+02, 1.48413159e+02, 1.48413159e+02],
       [2.71828183e+00, 2.71828183e+00, 2.71828183e+00],
       [2.98095799e+03, 2.98095799e+03, 2.98095799e+03]])

In [146]:
ny.log10(t5)

array([[0.69897   , 0.69897   , 0.69897   ],
       [0.        , 0.        , 0.        ],
       [0.90308999, 0.90308999, 0.90308999]])

In [189]:
ny.logspace(t5)

TypeError: _logspace_dispatcher() missing 1 required positional argument: 'stop'

In [183]:
# ny.random.seed(3)
ny.random.rand(3,3)

array([[0.44080984, 0.02987621, 0.45683322],
       [0.64914405, 0.27848728, 0.6762549 ],
       [0.59086282, 0.02398188, 0.55885409]])

In [46]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [47]:
i=0
while(i<10):
    i +=1
    print(i)

1
2
3
4
5
6
7
8
9
10


In [4]:
#  1.  4 indicates the number of matrices will be formed
#  2.  3   indicates the number of rows in each matrix
#  3.& 5  indicates the number of columns in each matrix
ny.random.randint(0,9,(4,3,5))

array([[[6, 1, 3, 7, 7],
        [8, 7, 6, 0, 2],
        [2, 1, 4, 4, 5]],

       [[0, 0, 4, 0, 2],
        [4, 5, 8, 4, 4],
        [3, 7, 7, 1, 2]],

       [[5, 4, 4, 8, 1],
        [1, 0, 7, 8, 3],
        [2, 5, 1, 5, 5]],

       [[7, 6, 6, 1, 0],
        [1, 1, 6, 7, 7],
        [8, 2, 4, 3, 1]]])